# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_build4520.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 582)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 480, 781, 91))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 781, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 90, 195, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 60, 195, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 120, 195, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_4.addWidget(self.lineEdit_4)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_4.setGeometry(QtCore.QRect(230, 30, 191, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_5.addWidget(self.lineEdit_5)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_5.setGeometry(QtCore.QRect(230, 60, 191, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_5)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_6.addWidget(self.lineEdit_6)
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_6.setGeometry(QtCore.QRect(230, 90, 121, 22))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_6)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_6)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_7.addWidget(self.lineEdit_7)
        self.layoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_7.setGeometry(QtCore.QRect(230, 120, 121, 22))
        self.layoutWidget_7.setObjectName("layoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_7)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget_7)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_8.addWidget(self.lineEdit_8)
        self.layoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_8.setGeometry(QtCore.QRect(460, 30, 181, 22))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_8)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_9.addWidget(self.label_9)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget_8)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_9.addWidget(self.lineEdit_9)
        self.layoutWidget_9 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_9.setGeometry(QtCore.QRect(460, 60, 101, 22))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_9)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_10.addWidget(self.label_10)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget_9)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_10.addWidget(self.lineEdit_10)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 195, 22))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_10 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_10.setGeometry(QtCore.QRect(470, 20, 171, 22))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_10)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_11.addWidget(self.label_11)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget_10)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_11.addWidget(self.lineEdit_11)
        self.layoutWidget_11 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_11.setGeometry(QtCore.QRect(10, 50, 195, 22))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_11)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_12.addWidget(self.label_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_11)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_12.addWidget(self.lineEdit_12)
        self.layoutWidget_12 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_12.setGeometry(QtCore.QRect(230, 20, 191, 22))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_12)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget_12)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_13.addWidget(self.lineEdit_13)
        self.layoutWidget_13 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_13.setGeometry(QtCore.QRect(10, 110, 195, 22))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_13)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_14.addWidget(self.label_14)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget_13)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_14.addWidget(self.lineEdit_14)
        self.layoutWidget_14 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_14.setGeometry(QtCore.QRect(230, 80, 121, 22))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_14)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_14)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_15.addWidget(self.lineEdit_15)
        self.layoutWidget_15 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_15.setGeometry(QtCore.QRect(230, 110, 121, 22))
        self.layoutWidget_15.setObjectName("layoutWidget_15")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.layoutWidget_15)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_15)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_15)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_16.addWidget(self.lineEdit_16)
        self.layoutWidget_16 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_16.setGeometry(QtCore.QRect(230, 50, 191, 22))
        self.layoutWidget_16.setObjectName("layoutWidget_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.layoutWidget_16)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_16)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_17.addWidget(self.label_17)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_16)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_17.addWidget(self.lineEdit_17)
        self.layoutWidget_17 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_17.setGeometry(QtCore.QRect(10, 80, 195, 22))
        self.layoutWidget_17.setObjectName("layoutWidget_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.layoutWidget_17)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_17)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_18.addWidget(self.label_18)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_17)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_18.addWidget(self.lineEdit_18)
        self.layoutWidget_18 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_18.setGeometry(QtCore.QRect(10, 20, 195, 22))
        self.layoutWidget_18.setObjectName("layoutWidget_18")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.layoutWidget_18)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_18)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_19.addWidget(self.label_19)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_18)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_19.addWidget(self.lineEdit_19)
        self.layoutWidget_19 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_19.setGeometry(QtCore.QRect(470, 50, 101, 22))
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.layoutWidget_19)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_19)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_20.addWidget(self.label_20)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_19)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_20.addWidget(self.lineEdit_20)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_20 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_20.setGeometry(QtCore.QRect(480, 50, 101, 22))
        self.layoutWidget_20.setObjectName("layoutWidget_20")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget_20)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_20)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_21.addWidget(self.label_21)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_20)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_21.addWidget(self.lineEdit_21)
        self.layoutWidget_21 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_21.setGeometry(QtCore.QRect(230, 50, 191, 22))
        self.layoutWidget_21.setObjectName("layoutWidget_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.layoutWidget_21)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_21)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_22.addWidget(self.label_22)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_21)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_22.addWidget(self.lineEdit_22)
        self.layoutWidget_22 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_22.setGeometry(QtCore.QRect(10, 80, 195, 22))
        self.layoutWidget_22.setObjectName("layoutWidget_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.layoutWidget_22)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_22)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_23.addWidget(self.label_23)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_22)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_23.addWidget(self.lineEdit_23)
        self.layoutWidget_23 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_23.setGeometry(QtCore.QRect(10, 110, 195, 22))
        self.layoutWidget_23.setObjectName("layoutWidget_23")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.layoutWidget_23)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_23)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_24.addWidget(self.label_24)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_23)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_24.addWidget(self.lineEdit_24)
        self.layoutWidget_24 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_24.setGeometry(QtCore.QRect(480, 20, 161, 22))
        self.layoutWidget_24.setObjectName("layoutWidget_24")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.layoutWidget_24)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_24)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_24)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_25.addWidget(self.lineEdit_25)
        self.layoutWidget_25 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_25.setGeometry(QtCore.QRect(230, 80, 121, 22))
        self.layoutWidget_25.setObjectName("layoutWidget_25")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.layoutWidget_25)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_25)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_26.addWidget(self.label_26)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_25)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_26.addWidget(self.lineEdit_26)
        self.layoutWidget_26 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_26.setGeometry(QtCore.QRect(10, 20, 195, 22))
        self.layoutWidget_26.setObjectName("layoutWidget_26")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.layoutWidget_26)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_26)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_26)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_27.addWidget(self.lineEdit_27)
        self.layoutWidget_27 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_27.setGeometry(QtCore.QRect(230, 20, 191, 22))
        self.layoutWidget_27.setObjectName("layoutWidget_27")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.layoutWidget_27)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_27)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget_27)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_28.addWidget(self.lineEdit_28)
        self.layoutWidget_28 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_28.setGeometry(QtCore.QRect(10, 50, 195, 22))
        self.layoutWidget_28.setObjectName("layoutWidget_28")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.layoutWidget_28)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_28)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_29.addWidget(self.label_29)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget_28)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_29.addWidget(self.lineEdit_29)
        self.layoutWidget_29 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_29.setGeometry(QtCore.QRect(230, 110, 121, 22))
        self.layoutWidget_29.setObjectName("layoutWidget_29")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.layoutWidget_29)
        self.horizontalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget_29)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_30.addWidget(self.label_30)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget_29)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_30.addWidget(self.lineEdit_30)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(690, 120, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "移动（0）："))
        self.label_2.setText(_translate("MainWindow", "备用IP:"))
        self.lineEdit_2.setText(_translate("MainWindow", "10.138.16.133"))
        self.label_3.setText(_translate("MainWindow", "主用端口:"))
        self.lineEdit_3.setText(_translate("MainWindow", "29010"))
        self.label_4.setText(_translate("MainWindow", "备用端口:"))
        self.lineEdit_4.setText(_translate("MainWindow", "29010"))
        self.label_5.setText(_translate("MainWindow", "3G-APN:"))
        self.lineEdit_5.setText(_translate("MainWindow", "dlgprscj.ah"))
        self.label_6.setText(_translate("MainWindow", "4G-APN:"))
        self.lineEdit_6.setText(_translate("MainWindow", "cmiotytx.ah"))
        self.label_7.setText(_translate("MainWindow", "用户名:"))
        self.label_8.setText(_translate("MainWindow", "密码:"))
        self.label_9.setText(_translate("MainWindow", "代理服务器地址:"))
        self.lineEdit_9.setText(_translate("MainWindow", "0.0.0.0"))
        self.label_10.setText(_translate("MainWindow", "代理端口:"))
        self.lineEdit_10.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "主用IP:"))
        self.lineEdit.setText(_translate("MainWindow", "10.138.16.133"))
        self.groupBox_3.setTitle(_translate("MainWindow", "电信（1）："))
        self.label_11.setText(_translate("MainWindow", "代理服务器地址:"))
        self.lineEdit_11.setText(_translate("MainWindow", "0.0.0.0"))
        self.label_12.setText(_translate("MainWindow", "主用端口:"))
        self.lineEdit_12.setText(_translate("MainWindow", "29010"))
        self.label_13.setText(_translate("MainWindow", "3G-APN:"))
        self.lineEdit_13.setText(_translate("MainWindow", "dlcdma.vpdn.ah"))
        self.label_14.setText(_translate("MainWindow", "备用端口:"))
        self.lineEdit_14.setText(_translate("MainWindow", "29010"))
        self.label_15.setText(_translate("MainWindow", "用户名:"))
        self.lineEdit_15.setText(_translate("MainWindow", "yzwx@dlcdma.vpdn.ah"))
        self.label_16.setText(_translate("MainWindow", "密码:"))
        self.lineEdit_16.setText(_translate("MainWindow", "123456"))
        self.label_17.setText(_translate("MainWindow", "4G-APN:"))
        self.lineEdit_17.setText(_translate("MainWindow", "dlcb.vpn.ah"))
        self.label_18.setText(_translate("MainWindow", "备用IP:"))
        self.lineEdit_18.setText(_translate("MainWindow", "10.138.16.133"))
        self.label_19.setText(_translate("MainWindow", "主用IP:"))
        self.lineEdit_19.setText(_translate("MainWindow", "10.138.16.133"))
        self.label_20.setText(_translate("MainWindow", "代理端口:"))
        self.lineEdit_20.setText(_translate("MainWindow", "0"))
        self.groupBox_2.setTitle(_translate("MainWindow", "联通（2）："))
        self.label_21.setText(_translate("MainWindow", "代理端口:"))
        self.lineEdit_21.setText(_translate("MainWindow", "0"))
        self.label_22.setText(_translate("MainWindow", "4G-APN:"))
        self.lineEdit_22.setText(_translate("MainWindow", "ahbzgwdl01.zncb.njm2mapn"))
        self.label_23.setText(_translate("MainWindow", "备用IP:"))
        self.lineEdit_23.setText(_translate("MainWindow", "10.138.16.133"))
        self.label_24.setText(_translate("MainWindow", "备用端口:"))
        self.lineEdit_24.setText(_translate("MainWindow", "29010"))
        self.label_25.setText(_translate("MainWindow", "代理服务器地址:"))
        self.lineEdit_25.setText(_translate("MainWindow", "0.0.0.0"))
        self.label_26.setText(_translate("MainWindow", "用户名:"))
        self.label_27.setText(_translate("MainWindow", "主用IP:"))
        self.lineEdit_27.setText(_translate("MainWindow", "10.138.16.133"))
        self.label_28.setText(_translate("MainWindow", "3G-APN:"))
        self.lineEdit_28.setText(_translate("MainWindow", "hfgdj.yccj.ahapn"))
        self.label_29.setText(_translate("MainWindow", "主用端口:"))
        self.lineEdit_29.setText(_translate("MainWindow", "29010"))
        self.label_30.setText(_translate("MainWindow", "密码:"))
        self.pushButton.setText(_translate("MainWindow", "生成"))

